/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:96d017e0-5abd-4313-896a-82a7dace0e83",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YdxV1Ktn3",
    "aws_user_pools_web_client_id": "66egc9bh98ip3nihl2n5ujn7rt",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "fridgeTable-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "fridgeApi",
            "endpoint": "https://iz0zsdoo08.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
